"""
Seed script to create ~20 realistic events across Georgia for users with id 3 and 8.
Usage:
    python seed_events.py          # create events
    python seed_events.py --reset  # delete existing events for users 3 & 8, then recreate
"""

from dotenv import load_dotenv

load_dotenv()

from app import create_app, db
from app.models import Event
from datetime import datetime, timedelta
import sys

app = create_app('development')

EVENTS = [
    {
        "host_id": 3,
        "title": "Sunrise Hike to Gergeti Trinity Church",
        "description": "One of Georgia's most iconic hikes — up to the medieval Gergeti Trinity Church at 2170m with Mount Kazbegi towering behind it. Moderate difficulty, ~4 hours up and back. We meet at the Stepantsminda town square at 5am to catch the sunrise at the top.",
        "event_time": datetime.now() ,
        "location_text": "Stepantsminda, Kazbegi",
        "lat": 42.6597,
        "lng": 44.6370,
        "category": "Sport",
        "mood_tags": "adventure, nature, early-bird",
        "capacity_min": 4,
        "capacity_max": 20,
        "price": 0.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Batumi Beach Volleyball Tournament",
        "description": "Friendly 3v3 beach volleyball tournament on the Black Sea shore. Teams of 3, round-robin format. Prizes for the winning team. Register as a team or we'll pair you with others.",
        "event_time": datetime.now() + timedelta(days=7, hours=10),
        "location_text": "Batumi Beach, Adjara",
        "lat": 41.6415,
        "lng": 41.6419,
        "category": "Sport",
        "mood_tags": "competitive, outdoor, beach",
        "capacity_min": 12,
        "capacity_max": 48,
        "price": 5.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Kakheti Wine Tour: Cellar Hopping",
        "description": "Visit three family-owned wineries in the Alazani Valley. Taste amber wines straight from qvevri, walk the vineyards, and learn about ancient Georgian winemaking. Transport from Telavi provided. Lunch included.",
        "event_time": datetime.now() + timedelta(days=9, hours=10),
        "location_text": "Telavi, Kakheti",
        "lat": 41.9200,
        "lng": 45.4767,
        "category": "Food & Drink",
        "mood_tags": "cultural, relaxed, scenic",
        "capacity_min": 6,
        "capacity_max": 18,
        "price": 80.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Svaneti Photography Expedition",
        "description": "4-day photography trip through Upper Svaneti — medieval towers, glaciers, and mountain villages. We'll visit Ushguli, one of the highest inhabited villages in Europe. Limited to 8 people for an intimate experience. Accommodation arranged.",
        "event_time": datetime.now() + timedelta(days=14, hours=7),
        "location_text": "Mestia, Svaneti",
        "lat": 43.0530,
        "lng": 42.7277,
        "category": "Art",
        "mood_tags": "adventure, creative, scenic",
        "capacity_min": 4,
        "capacity_max": 8,
        "price": 350.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Borjomi Mineral Water Spa Day",
        "description": "Relax in the famous Borjomi mineral water pools surrounded by forested mountains. We'll meet at the park entrance, spend the day at the spa, and have dinner at a local restaurant before heading back.",
        "event_time": datetime.now() + timedelta(days=4, hours=11),
        "location_text": "Borjomi Central Park, Samtskhe-Javakheti",
        "lat": 41.8361,
        "lng": 43.4003,
        "category": "Wellness",
        "mood_tags": "relaxing, nature, wellness",
        "capacity_min": 4,
        "capacity_max": 15,
        "price": 40.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Sighnaghi Art Residency Weekend",
        "description": "Two days of painting and sketching in the City of Love. We'll work en plein air overlooking the Alazani Valley and Caucasus peaks. Evening polyphonic singing session included. Accommodation in a guesthouse.",
        "event_time": datetime.now() + timedelta(days=11, hours=15),
        "location_text": "Sighnaghi, Kakheti",
        "lat": 41.6157,
        "lng": 45.9215,
        "category": "Art",
        "mood_tags": "creative, romantic, cultural",
        "capacity_min": 5,
        "capacity_max": 12,
        "price": 150.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Kutaisi Cave Tour: Prometheus & Sataplia",
        "description": "Full day tour of two of Georgia's most spectacular caves. Morning at Prometheus Cave with its dramatic stalactites, afternoon at Sataplia with dinosaur footprints and a glass-floor viewpoint. Transport from Kutaisi city center included.",
        "event_time": datetime.now() + timedelta(days=6, hours=9),
        "location_text": "Kutaisi, Imereti",
        "lat": 42.2679,
        "lng": 42.6956,
        "category": "Education",
        "mood_tags": "nature, adventure, educational",
        "capacity_min": 5,
        "capacity_max": 20,
        "price": 55.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Batumi Jazz Festival Pre-Party",
        "description": "Warm-up evening ahead of the Batumi Jazz Festival. Local jazz quartet playing on the seafront boulevard. Bring a blanket, grab some churchkhela from the vendors, and enjoy the Black Sea breeze.",
        "event_time": datetime.now() + timedelta(days=3, hours=20),
        "location_text": "Batumi Boulevard, Adjara",
        "lat": 41.6488,
        "lng": 41.6406,
        "category": "Music",
        "mood_tags": "festive, outdoor, cultural",
        "capacity_min": 20,
        "capacity_max": 300,
        "price": 0.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Mtskheta Historical Walking Tour",
        "description": "Guided walk through Mtskheta, the ancient capital and spiritual heart of Georgia. We'll visit Svetitskhoveli Cathedral, Jvari Monastery, and lesser-known churches. Local historian leads the tour. Duration: ~3 hours.",
        "event_time": datetime.now() + timedelta(days=2, hours=10),
        "location_text": "Mtskheta, near Tbilisi",
        "lat": 41.8452,
        "lng": 44.7202,
        "category": "Education",
        "mood_tags": "cultural, historical, scenic",
        "capacity_min": 5,
        "capacity_max": 25,
        "price": 20.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Vardzia Cave Monastery Day Trip",
        "description": "Visit the 12th century cave city of Vardzia carved into the volcanic rock of the Erusheti Mountain. Over 600 rooms, a church with original frescoes, and sweeping Mtkvari valley views. Bus departs from Akhaltsikhe.",
        "event_time": datetime.now() + timedelta(days=16, hours=9),
        "location_text": "Vardzia, Samtskhe-Javakheti",
        "lat": 41.3817,
        "lng": 43.2817,
        "category": "Education",
        "mood_tags": "historical, adventure, scenic",
        "capacity_min": 8,
        "capacity_max": 30,
        "price": 35.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Rafting on the Rioni River",
        "description": "Half-day white water rafting on the Rioni River through the Imereti gorges. Class III-IV rapids. All equipment and safety gear provided. No experience needed — guides will brief you fully. Min age 16.",
        "event_time": datetime.now() + timedelta(days=8, hours=9, minutes=30),
        "location_text": "Oni, Racha-Lechkhumi",
        "lat": 42.5867,
        "lng": 43.4506,
        "category": "Sport",
        "mood_tags": "adventure, adrenaline, nature",
        "capacity_min": 6,
        "capacity_max": 16,
        "price": 70.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Tbilisi Rooftop Polyphony Concert",
        "description": "An evening of traditional Georgian polyphonic singing on a rooftop in Sololaki. Three ensembles performing pieces from Kartli, Kakheti, and Svaneti. One of Georgia's UNESCO-recognized treasures performed under the stars.",
        "event_time": datetime.now() + timedelta(days=10, hours=20),
        "location_text": "Sololaki, Tbilisi",
        "lat": 41.6892,
        "lng": 44.8034,
        "category": "Music",
        "mood_tags": "cultural, atmospheric, traditional",
        "capacity_min": 20,
        "capacity_max": 60,
        "price": 35.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Cycling the Alazani Valley",
        "description": "One-day cycling route through the vineyards and villages of the Alazani Valley. ~40km, mostly flat. Bike rental available in Telavi for 30 GEL. We'll stop for wine and churchkhela along the way. Beginner-friendly pace.",
        "event_time": datetime.now() + timedelta(days=12, hours=8),
        "location_text": "Telavi to Alaverdi, Kakheti",
        "lat": 41.9200,
        "lng": 45.4767,
        "category": "Sport",
        "mood_tags": "scenic, active, nature",
        "capacity_min": 4,
        "capacity_max": 16,
        "price": 0.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Chacha Tasting & Distillery Visit",
        "description": "Tour a family chacha distillery in Kakheti and taste 5 different varieties — grape, mulberry, fig, and more. Learn the distillation process and take home a bottle. Transport from Tbilisi available for 15 GEL extra.",
        "event_time": datetime.now() + timedelta(days=17, hours=14),
        "location_text": "Gurjaani, Kakheti",
        "lat": 41.7467,
        "lng": 45.8078,
        "category": "Food & Drink",
        "mood_tags": "cultural, fun, social",
        "capacity_min": 6,
        "capacity_max": 20,
        "price": 50.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Paragliding over Gudauri",
        "description": "Tandem paragliding flight over the Greater Caucasus from Gudauri ski resort (2200m). Flights last 15-20 minutes with panoramic mountain views. Professional pilots, full safety briefing. Book your slot — only 6 flights per session.",
        "event_time": datetime.now() + timedelta(days=19, hours=11),
        "location_text": "Gudauri, Mtskheta-Mtianeti",
        "lat": 42.4667,
        "lng": 44.4833,
        "category": "Sport",
        "mood_tags": "adrenaline, adventure, scenic",
        "capacity_min": 2,
        "capacity_max": 6,
        "price": 180.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Gori Food Market & Stalin Museum Visit",
        "description": "Morning at Gori's lively food market — fresh produce, local cheese, tklapi, and more. Afternoon visit to the Stalin Museum (love it or hate it, it's fascinating). Lunch at a family restaurant between the two. Day trip from Tbilisi.",
        "event_time": datetime.now() + timedelta(days=13, hours=9),
        "location_text": "Gori, Shida Kartli",
        "lat": 41.9851,
        "lng": 44.1133,
        "category": "Community",
        "mood_tags": "cultural, historical, foodie",
        "capacity_min": 5,
        "capacity_max": 20,
        "price": 25.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Batumi Botanical Garden Picnic",
        "description": "Picnic in one of the most beautiful botanical gardens in the Caucasus, perched above the Black Sea. 108 hectares of subtropical plants from around the world. BYO food and drinks — we'll find a great spot together.",
        "event_time": datetime.now() + timedelta(days=15, hours=12),
        "location_text": "Batumi Botanical Garden, Adjara",
        "lat": 41.7167,
        "lng": 41.6833,
        "category": "Community",
        "mood_tags": "relaxed, nature, social",
        "capacity_min": 5,
        "capacity_max": 30,
        "price": 10.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Stargazing Night: Javakheti Plateau",
        "description": "The Javakheti highland plateau has some of the darkest skies in Georgia. We'll drive up after sunset, set up telescopes, and spend 3 hours stargazing with an amateur astronomer guide. Warm clothes essential — it gets cold at 2000m.",
        "event_time": datetime.now() + timedelta(days=20, hours=21),
        "location_text": "Javakheti Plateau, near Akhalkalaki",
        "lat": 41.4094,
        "lng": 43.4914,
        "category": "Education",
        "mood_tags": "peaceful, nature, educational",
        "capacity_min": 4,
        "capacity_max": 15,
        "price": 30.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "automatic",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 3,
        "title": "Horseback Riding in Tusheti",
        "description": "Half-day horseback ride through the remote alpine villages of Tusheti. One of Georgia's most isolated regions, accessible only by a legendary mountain road. Local guide and horses provided. Suitable for beginners.",
        "event_time": datetime.now() + timedelta(days=22, hours=9),
        "location_text": "Omalo, Tusheti",
        "lat": 42.2833,
        "lng": 45.3167,
        "category": "Sport",
        "mood_tags": "adventure, nature, remote",
        "capacity_min": 3,
        "capacity_max": 10,
        "price": 90.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
    {
        "host_id": 4,
        "title": "Kobuleti Sunset Yoga Retreat",
        "description": "Weekend yoga and meditation retreat on the Black Sea coast. Two days of morning yoga, breathwork, and evening meditation sessions. Vegetarian meals included. Accommodation in a beachside guesthouse. Max 10 participants for an intimate setting.",
        "event_time": datetime.now() + timedelta(days=18, hours=16),
        "location_text": "Kobuleti, Adjara",
        "lat": 41.8281,
        "lng": 41.7731,
        "category": "Wellness",
        "mood_tags": "wellness, peaceful, beach",
        "capacity_min": 4,
        "capacity_max": 10,
        "price": 200.0,
        "is_public": True,
        "currency": "GEL",
        "approval_mode": "manual",
        "participant_list_visible": True,
        "is_anonymous": False,
    },
]


def seed_events(reset=False):
    with app.app_context():
        if reset:
            deleted = Event.query.filter(Event.host_id.in_([3, 4])).delete(synchronize_session=False)
            db.session.commit()
            print(f"Deleted {deleted} existing events for users 3 and 4.")

        created = 0
        for data in EVENTS:
            event = Event(**data)
            db.session.add(event)
            created += 1

        db.session.commit()
        print(f"Created {created} events successfully.")


if __name__ == '__main__':
    reset = '--reset' in sys.argv
    seed_events(reset=reset)
