"""add is_blocked to user

Revision ID: 2d8324e47f9d
Revises: 69272bf1d08f
Create Date: 2026-06-06 23:06:31.700409

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d8324e47f9d'
down_revision = '69272bf1d08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET is_blocked = FALSE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')
    # ### end Alembic commands ###
