"""add role to user and is_anonymous to event

Revision ID: 69272bf1d08f
Revises: 76df0f5d8e4d
Create Date: 2026-06-06 22:57:23.038803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69272bf1d08f'
down_revision = '76df0f5d8e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookmarks_event_id_events'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookmarks_event_id_events'), 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
