"""add indexes
Revision ID: b826aa4a5003
Revises: 2f06858187d0
Create Date: 2026-04-29 01:41:54.519294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b826aa4a5003'
down_revision = '2f06858187d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bookmarks_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_event_time', ['event_time'], unique=False)
        batch_op.create_index('ix_events_host_id', ['host_id'], unique=False)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_follows_followed_id', ['followed_id'], unique=False)
        batch_op.create_index('ix_follows_follower_id', ['follower_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_messages_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index('ix_participations_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_participations_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index('ix_participations_user_id')
        batch_op.drop_index('ix_participations_event_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_user_id')
        batch_op.drop_index('ix_messages_event_id')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('ix_follows_follower_id')
        batch_op.drop_index('ix_follows_followed_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_host_id')
        batch_op.drop_index('ix_events_event_time')

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmarks_user_id')

    # ### end Alembic commands ###
