"""reporterr becomes nullable

Revision ID: fdd12d0254e6
Revises: 4e6c1f9eea36
Create Date: 2026-07-06 04:38:56.995514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd12d0254e6'
down_revision = '4e6c1f9eea36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
